post_build:
  commands:
    - echo Build completed on `date`
    - printf '[{"name":"linkbridge-web","imageUri":"%s"}]' $REPOSITORY_URI:latest > imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json